name: 'Chromatic'
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - uses: chromaui/action@v1
        with:
          workingDir: packages/react
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
